# Generated by Django 6.0.3 on 2026-03-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='ID',
            new_name='id',
        ),
    ]
