# Generated by Django 6.0.3 on 2026-03-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('OpenAlex', 'OpenAlex'), ('Scopus', 'Scopus'), ('Wos', 'Web of Science'), ('Crossref', 'Crossref'), ('Dimensions', 'Dimensions')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('citation_date', models.DateField(blank=True, null=True)),
                ('cited_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_received', to='publication.publication')),
                ('citing_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_made', to='publication.publication')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'db_table': 'citations',
                'unique_together': {('citing_publication', 'cited_publication')},
            },
        ),
    ]
