# Generated by Django 6.0.3 on 2026-03-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='openalex_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID OpenAlex de la citation : https://openalex.org/C1234567890', max_length=200, null=True, unique=True),
        ),
    ]
