# Generated by Django 6.0.3 on 2026-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('contribution_type', models.IntegerField(choices=[(1, 'First Author'), (2, 'Second Author'), (3, 'Third Author'), (4, 'Corresponding Author'), (5, 'Other')], default=1)),
                ('author_order', models.IntegerField(default=1)),
                ('affiliation_at_time', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'CoAuthor',
                'verbose_name_plural': 'CoAuthors',
                'db_table': 'coauthors',
            },
        ),
    ]
