# Generated by Django 6.0.3 on 2026-03-13 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coAuthor', '0001_initial'),
        ('publication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthored_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coauthor',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='publication.publication'),
        ),
        migrations.AlterUniqueTogether(
            name='coauthor',
            unique_together={('publication', 'author')},
        ),
    ]
