# Generated by Django 6.0.3 on 2026-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='openalex_id',
            field=models.CharField(blank=True, help_text='ID OpenAlex : https://openalex.org/W1234567890', max_length=200, null=True, unique=True),
        ),
    ]
