# Generated by Django 6.0.3 on 2026-03-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_publication_openalex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_Validated',
            field=models.BooleanField(default=True),
        ),
    ]
