# Generated by Django 6.0.3 on 2026-03-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_alter_publication_is_validated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='is_Validated',
            new_name='is_validated',
        ),
    ]
